### ISSUE TITLE
app.js is having scattered data and missing images

### ISSUE THREAD

**Issue by ahnafis** [MarufAlAslam/javascript-bangladesh-12th-election-information#1]
In `/js/app.js`, images that contain candidates of corresponding seat are missing. Also, I see most of the data are repeated unorganized.

If you could add those image URLs, I could organize and turn it to an efficient date set. Thank you in advance ❤️

**Comment by MarufAlAslam** [comment]
it's still in it's initial phase. and the images are still being generated, so it may take 2-3 days to organize and implement.
